name: hexagon
description: Library containing the logic for hexagon shapes, adopted from https://www.redblobgames.com/grids/hexagons/ and https://github.com/rSquared-software/flutter-hexagon
version: 0.1.0
homepage: https://github.com/CLNMR/flutter-hexagon

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  json_annotation: ^4.7.0

dev_dependencies: 
  build_runner: ^2.0.3
  json_serializable: ^6.5.4