name: hexagon_ui
description: Library to display hexagons created by the hexagon package.
version: 0.1.0
homepage: https://github.com/CLNMR/flutter-hexagon

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hexagon: ">=0.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: false

dependency_overrides:
  hexagon:
    path: ../hexagon
 